# Generated by Django 6.0.5 on 2026-05-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=100)),
                ('mes', models.CharField(max_length=7)),
                ('datos_json', models.JSONField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
